w4d2/ninetynine_cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats do
  	resources :cat_rental_requests, only: [:new, :create], as: "rental_request"
  end
  resources :cat_rental_requests, only: :destroy do
    get 'approve' => 'cat_rental_requests#approve', as: 'approval'
    get 'deny' => 'cat_rental_requests#deny', as: 'denial'
  end

  root :to => "cats#index"

end

w4d2/ninetynine_cats/app/models/cat.rb
class Cat < ActiveRecord::Base

  COLORS = ['grey', 'orange', 'white', 'black', 'tabby', 'brown']

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates_inclusion_of :sex, in: %w( M F )
  validates_inclusion_of :color, in: COLORS

  has_many :cat_rental_requests, dependent: :destroy

  def age
    now = Time.now.utc.to_date
    now.year - birth_date.year - (birth_date.change(:year => now.year) > now ? 1 : 0)
  end

  def not_denied_requests
    cat_rental_requests.where("status != 'DENIED'").order(:start_date)
  end

end

w4d2/ninetynine_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  after_initialize do |cat_rental_request|
    cat_rental_request.status ||= "PENDING"
  end

  validates :cat_id, :start_date, :end_date, presence: true
  validates_inclusion_of :status, in: %w(PENDING APPROVED DENIED), allow_nil: true
  validate :overlapping_approved_requests

  belongs_to :cat

  def approve!
    CatRentalRequest.transaction do
      self.update(status: "APPROVED")
      overlapping_pending_requests.each { |req| req.deny! }
    end
  end

  def deny!
    self.update(status: "DENIED")
  end

  def pending?
    status == "PENDING"
  end

  def approved?
    status == "APPROVED"
  end

  # private

  def overlapping_requests
    CatRentalRequest
      .where("(:id IS NULL) OR (id != :id)", id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
       NOT( (start_date > :end_date) OR (end_date < :start_date) )
    SQL

    # CatRentalRequest.find_by_sql(<<-SQL)
    # SELECT
    #   crr.*
    # FROM
    #   cat_rental_requests crr
    # WHERE
    #   crr.cat_id = #{cat_id} AND
    #   (
    #     (crr.start_date BETWEEN TO_DATE ('#{start_date}', 'yyyy-mm-dd') AND TO_DATE ('#{end_date}', 'yyyy-mm-dd' )) OR
    #     (crr.end_date BETWEEN TO_DATE ('#{start_date}', 'yyyy-mm-dd') AND TO_DATE ('#{end_date}', 'yyyy-mm-dd')) OR
    #     (
    #       crr.start_date <= TO_DATE ('#{start_date}', 'yyyy-mm-dd') AND
    #       crr.end_date >= TO_DATE ('#{end_date}', 'yyyy-mm-dd')
    #     )
    #   )
    # SQL
  end

  def overlapping_approved_requests
    overlapproved = overlapping_requests.select { |req| req.status == 'APPROVED' }
    return if overlapproved.empty? || status == "DENIED"
    errors[:start_date] << "date overlaps with another cat's date"
  end

  def overlapping_pending_requests
    overlapping_requests.select { |req| req.status == 'PENDING' }
  end

end

w4d2/ninetynine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

w4d2/ninetynine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @request = CatRentalRequest.new
    @request.cat_id = params[:cat_id]
    @cats = Cat.all
  end

  def create
    @request = CatRentalRequest.new(req_params)
    @cats = Cat.all
    if @request.save
      redirect_to cat_url(req_params[:cat_id])
    else
      render :new
    end
  end

  def approve
    @request = CatRentalRequest.find(params[:cat_rental_request_id])
    @request.approve!
    redirect_to cat_url(@request.cat_id)
  end

  def deny
    @request = CatRentalRequest.find(params[:cat_rental_request_id])
    @request.deny!
    redirect_to cat_url(@request.cat_id)
  end

  def destroy
    @request = CatRentalRequest.find(params[:id])
    CatRentalRequest.destroy(@request)
    redirect_to cat_url(@request.cat_id)
  end

  private

  def req_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end


end

w4d2/ninetynine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    Cat.destroy(@cat)
    redirect_to cats_url
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :sex, :description, :name)
  end

end

w4d2/ninetynine_cats/app/views/cat_rental_requests/new.html.erb
<div class="container">
  <h1>Request a Cat Rental</h1>

  <form action="<%= cat_rental_request_index_url %>" method="post">

    <div class="form-group">
      <label for="cat">Pick a Cat</label>
      <select name="cat_rental_request[cat_id]" class="form-control">
        <% @cats.each do |cat| %>
        <option value="<%= cat.id %>" <%= cat.id == @request.cat_id ? "selected" : "" %>>
          <%= cat.name %>
        </option>
        <% end %>
      </select>
    </div>

    <div class="form-group">
      <label for="req_start_date">Start date</label>
      <input name="cat_rental_request[start_date]" class="form-control" id="req_start_date" type="date"
      value="<%= @request.start_date.to_s %>"></input>
    </div>

    <div class="form-group">
      <label for="req_end_date">End date</label>
      <input name="cat_rental_request[end_date]" class="form-control" id="req_end_date" type="date"
      value="<%= @request.end_date.to_s %>"></input>

    </div> 

    <button type="submit" class="btn btn-primary">Submit a Request!</button>
    <%= link_to "Back to Index", cats_url, :class => "btn btn-danger" %>

  </form>
</div>

w4d2/ninetynine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>99 Cats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
	  <!-- <center><%= image_tag("images.jpeg", width:100) %><h1>99 CATS</h1></center> -->
	  <div class="page-header">
	   <h1 class="text-warning">NINETYNINE CATS</h1><%= image_tag("images.jpeg", align: 'right', width:100) %>
		</div>
		<p>Welcome to nintey-nine cats, the internet's one-stop shop for feline rentals. Be sure to browse our wide selection of pets who may or may not care whether you live or die.</p>
	 </div>

  <%= yield %>

</body>
</html>