w4d4/music_app/config/routes.rb
Rails.application.routes.draw do
  
  root to: 'bands#index'

  get '/login' => 'sessions#new'
  resource :session, only: [:create, :destroy]
  resources :users, only: [:index, :new, :create, :show] do
     get :activate, on: :collection
  end

  resources :bands do 
  	resource :albums, only: [:new], as: 'album'
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
  	resource :tracks, only: [:new], as: 'track'
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  
  resources :notes, only: [:create, :destroy]
end

w4d4/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  recording_type :string           not null
#  band_id        :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ActiveRecord::Base

	RECORDING_TYPES = ['live', 'studio']
	validates :name, :recording_type, :band, presence: true
	validates_inclusion_of :recording_type, in: RECORDING_TYPES
	belongs_to :band
	has_many :tracks, dependent: :destroy

end

w4d4/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

 # new_band_album GET    /bands/:band_id/albums/new(.:format)   albums#new
 #         albums POST   /albums(.:format)                      albums#create
 #     edit_album GET    /albums/:id/edit(.:format)             albums#edit
 #          album GET    /albums/:id(.:format)                  albums#show
 #                PATCH  /albums/:id(.:format)                  albums#update
 #                PUT    /albums/:id(.:format)                  albums#update
 #                DELETE /albums/:id(.:format)                  albums#destroy

 before_action :verify_authorization, only: [:new, :create, :edit, :update, :destroy]
 
 def show
 	@album = Album.find(params[:id])
 	@band = @album.band
 	@tracks = @album.tracks
 end
 
 def new
 	@band = Band.find(params[:band_id])
 	@album = @band.albums.new

 	render :new
 end

 def create
 	@album = Album.new(album_params)
 	@band = Band.find(album_params[:band_id])

 	if @album.save
 		redirect_to band_url(@album.band.id)
 	else
 		flash[:errors] = @album.errors.full_messages
 		render :new
 	end
 end

 def edit
 	@album = Album.find(params[:id])
 	@band = @album.band
 	render :edit
 end

 def update
 	@album = Album.find(params[:id])
 	@band = @album.band

 	if @album.update(album_params)
 		redirect_to band_url(@album.band.id)
 	else
 		flash[:errors] = @album.errors.full_messages
 		render :edit
 	end
 end

 def destroy
 	@album = Album.find(params[:id])
 	@album.destroy
 	redirect_to band_url(@album.band.id)
 end

 private

 def album_params
 	params.require(:album).permit(:name, :recording_type, :band_id)
 end

 	def verify_authorization
		redirect_to login_url unless current_user
	end

 
end

w4d4/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

w4d4/music_app/app/views/albums/_album_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>
<% submit_txt = (album.persisted? ? "Update Album" : "Create Album") %>

<%= render '/layouts/errors' %>

<form action="<%= action %>" method="POST">

	<input type='hidden' name='_method' value="<%= method %>" %>
	<input type='hidden' name="album[band_id]" value="<%=album.band_id%>" %>
	<%= render '/layouts/form_authenticity' %>


	<%= render '/layouts/form_dropdown',
						label_name: 'Band Name',
						key: 'album',
						col_name: 'band_id',
						arr: Band.all,
						selected: album.band_id %>

	<br>

	<%= render 'layouts/form_text', 
							label_name: 'Album Name',
							key: 'album',
							col_name: 'name',
							default_value: album.name %>
	

	<br>

	<%= render '/layouts/form_radio',
						label_name: 'Recording Type',
						key: 'album',
						col_name: 'recording_type',
						arr: Album::RECORDING_TYPES,
						selected: album.recording_type %>
						
	<br>

	<input type="submit" value="<%=submit_txt%>">

</form>

w4d4/music_app/app/views/albums/edit.html.erb
<h1><%= @band.name %> | Edit Album</h1>
<%= render 'album_form', album: @album %>

w4d4/music_app/app/views/albums/new.html.erb
<h1><%= @band.name %> | New Album</h1>
<%= render 'album_form', album: @album %>

w4d4/music_app/app/views/albums/show.html.erb
<h1> <%= link_to @band.name, band_url(@band) %> | <%= @album.name %> </h1>

<h3>Tracks</h3>
<ol>
	<% @tracks.each do |track| %>
		<li>
			<%= link_to "#{track.name}", track_url(track) %>
			<div style='display:inline-block;'>
				<%= button_to 'edit', edit_track_url(track), method: :get %>
			</div>
			<div style='display:inline-block;'>
				<%= button_to 'delete', track_url(track), method: :delete %>
			</div>
		</li>
	<% end %>
</ol>

<%= link_to 'Create a New Track', new_album_track_url(@album) %>